global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Numerics;
global using Dalamud.Bindings.ImGui;
global using Dalamud.Interface.Utility;
global using Dalamud.Interface.Utility.Raii;
global using Dalamud.Interface.Windowing;
global using Dalamud.Plugin;
global using Dalamud.Plugin.Services;
global using MirageUI;
global using MirageUI.Fonts;
global using MirageUI.Ui;
global using MirageUI.Theme;
global using static MirageUiSample.Plugin;
global using static MirageUI.Ui.MirageLayout;
